### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by abhitechdojo** [kijiproject/kiji#2]
I am followed the steps given here 

git clone https://github.com/kijiproject/kiji
cd kiji
 ./bin/kiji-build build 

and I am getting this error

20150902-112722-082-CDT ERROR maven_wrapper.py:560 : Error parsing Maven project definition in path=None (parent=None)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Frepository.codehaus.org%2Fcom%2Fhadoop%2Fgplcompression%2Fhadoop-lzo%2F0.4.16%2Fhadoop-lzo-0.4.16.pom&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Frepository.codehaus.org%2Fcom%2Fhadoop%2Fgplcompression%2Fhadoop-lzo%2F0.4.16%2Fhadoop-lzo-0.4.16.pom&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>
20150902-112722-095-CDT ERROR maven_wrapper.py:428 : Error parsing Maven project definition for com.hadoop.gplcompression:hadoop-lzo:0.4.16
20150902-112722-095-CDT ERROR maven_loader.py:267 : Error in Maven dependency scanner worker thread: ExpatError('not well-formed (invalid token): line 1, column 268',)
Traceback (most recent call last):
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 265, in _worker_thread
    self._worker_thread_unsafe()
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 285, in _worker_thread_unsafe
    entry = self._visit_dep(dep_chain)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 131, in _visit_dep
    project = self.wkspc.GetOrFetchForArtifact(artifact=project_artf)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 429, in GetOrFetchForArtifact
    raise err
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 425, in GetOrFetchForArtifact
    project = MavenProject(workspace=self, pom_xml=pom_xml)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 561, in __init__
    raise err
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 556, in __init__
    self._dom = xml_util.parse_from_string(text=self._pom_xml)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/util/xml_util.py", line 27, in parse_from_string
    return minidom.parseString(text)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/minidom.py", line 1970, in parseString
    return expatbuilder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 268
20150902-112722-214-CDT ERROR workflow_task.py:207 : Failure for '//org/kiji/express:kiji-express-lib'
20150902-112722-231-CDT INFO workflow_task.py:215 :     Failed '//org/kiji/express:kiji-express-lib' in 12.218s
20150902-112722-241-CDT ERROR workflow.py:891 : Unhandled exception from Task.run() for <class 'wibi.build.workflow_task.ScalaLibraryTask'>:
Traceback (most recent call last):
  File "/Users/abhi/kiji-bento/kiji/python/workflow/src/main/python/workflow/workflow.py", line 312, in _run
    self._state = self.run()
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/build/workflow_task.py", line 204, in run
    result = super().run()
  File "/Users/abhi/kiji-bento/kiji/python/workflow/src/main/python/workflow/workflow.py", line 1586, in run
    task_state = self.run_with_io(output=output, **input_map)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/build/workflow_task.py", line 1981, in run_with_io
    resolved_build_deps = sorted(resolved_build_deps)
  File "/Users/abhi/kiji-bento/kiji/devtools/src/main/python/wibi/build/build_tools.py", line 697, in resolve_deps
    ("%d errors while resolving Maven dependencies" % len(scanner.errors))
AssertionError: 1 errors while resolving Maven dependencies

20150902-112722-252-CDT INFO base.py:590 : Forcibly terminating program (PID=8361)
./bin/kiji-build: line 81:  8361 Killed: 9               "${venv_root}"/bin/python3 -m wibi.scripts.kiji_build "$@"
Mohitas-MBP:kiji abhi$

**Comment by gwu** [comment]
It looks like the pom file in your local repo for com.hadoop.gplcompression:hadoop-lzo:0.4.16 is wonky. Can you try removing it from your ~/.m2/repository (~/.m2/repository/com/hadoop/gplcompression/hadoop-lzo/...) and try again?

**Comment by abhitechdojo** [comment]
Here is what I did 

```
cd /Users/abhi/.m2/repository/com/hadoop/gplcompression/hadoop-lzo/0.4.16
mv hadoop-lzo-0.4.16.pom hadoop-lzo-0.4.16.bak
```

But I still got this error

20150910-110255-481-CDT ERROR maven_wrapper.py:560 : Error parsing Maven project definition in path=None (parent=None)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Frepository.codehaus.org%2Fcom%2Fhadoop%2Fgplcompression%2Fhadoop-lzo%2F0.4.16%2Fhadoop-lzo-0.4.16.pom&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://searchassist.verizon.com/main?ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Frepository.codehaus.org%2Fcom%2Fhadoop%2Fgplcompression%2Fhadoop-lzo%2F0.4.16%2Fhadoop-lzo-0.4.16.pom&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>
20150910-110255-482-CDT ERROR maven_wrapper.py:428 : Error parsing Maven project definition for com.hadoop.gplcompression:hadoop-lzo:0.4.16
20150910-110255-482-CDT ERROR maven_loader.py:267 : Error in Maven dependency scanner worker thread: ExpatError('not well-formed (invalid token): line 1, column 268',)
Traceback (most recent call last):
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 265, in _worker_thread
    self._worker_thread_unsafe()
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 285, in _worker_thread_unsafe
    entry = self._visit_dep(dep_chain)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_loader.py", line 131, in _visit_dep
    project = self.wkspc.GetOrFetchForArtifact(artifact=project_artf)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 429, in GetOrFetchForArtifact
    raise err
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 425, in GetOrFetchForArtifact
    project = MavenProject(workspace=self, pom_xml=pom_xml)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 561, in __init__
    raise err
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/maven/maven_wrapper.py", line 556, in __init__
    self._dom = xml_util.parse_from_string(text=self._pom_xml)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/util/xml_util.py", line 27, in parse_from_string
    return minidom.parseString(text)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/minidom.py", line 1970, in parseString
    return expatbuilder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 268
20150910-110255-493-CDT ERROR workflow_task.py:207 : Failure for '//org/kiji/express:kiji-express-lib'
20150910-110255-494-CDT INFO workflow_task.py:215 :     Failed '//org/kiji/express:kiji-express-lib' in 101.391s
20150910-110255-497-CDT ERROR workflow.py:891 : Unhandled exception from Task.run() for <class 'wibi.build.workflow_task.ScalaLibraryTask'>:
Traceback (most recent call last):
  File "/Users/abhi/kiji/python/workflow/src/main/python/workflow/workflow.py", line 312, in _run
    self._state = self.run()
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/build/workflow_task.py", line 204, in run
    result = super().run()
  File "/Users/abhi/kiji/python/workflow/src/main/python/workflow/workflow.py", line 1586, in run
    task_state = self.run_with_io(output=output, **input_map)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/build/workflow_task.py", line 1981, in run_with_io
    resolved_build_deps = sorted(resolved_build_deps)
  File "/Users/abhi/kiji/devtools/src/main/python/wibi/build/build_tools.py", line 697, in resolve_deps
    ("%d errors while resolving Maven dependencies" % len(scanner.errors))
AssertionError: 1 errors while resolving Maven dependencies

20150910-110255-498-CDT INFO base.py:590 : Forcibly terminating program (PID=765)
./bin/kiji-build: line 81:   765 Killed: 9               "${venv_root}"/bin/python3 -m wibi.scripts.kiji_build "$@"
Mohitas-MBP:kiji abhi$
